name: Build and test CLI tool

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        working-directory: ./touls
        run: cargo build --verbose

      - name: Run tests
        working-directory: ./touls
        run: cargo test --verbose
